### ISSUE TITLE
Run hexo algolia error, how to solve?

### ISSUE THREAD

**Issue by neroxps** [oncletom/hexo-algolia#15]
```
NerodeMBP:Blog-hexo nero$ hexo algolia
(node:2795) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
INFO  [Algolia] Testing HEXO_ALGOLIA_INDEXING_KEY permissions.
INFO  Start processing
INFO  [Algolia] Identified 25 posts to index.
INFO  [Algolia] Start indexing...
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error
    at success (/Users/nero/Blog-hexo/node_modules/algoliasearch/src/AlgoliaSearchCore.js:351:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

**Comment by thom4parisot** [comment]
Hm, strange: which version of hexo, hexo-algolia and Node do you use?
Did it work in the past?

When you type `echo $HEXO_ALGOLIA_INDEXING_KEY`, does it print something?

What is the value of the `_config.yml` in the `algolia` block? (clear our the apiKey when you paste just in case it would enable to write in the index).

**Comment by xkcoding** [comment]
HEXO_ALGOLIA_INDEXING_KEY what should i set?

**Comment by thom4parisot** [comment]
@xkcoding I can only encourage you to have a look at the [README _Indexing Content_ section](https://github.com/oncletom/hexo-algolia#indexing-content). Tell me if it can be made clearer 🙂

**Comment by xkcoding** [comment]
i set the environment variable but still have the problem 
![image](https://user-images.githubusercontent.com/10429917/28613476-0a2c1bb0-7225-11e7-940a-f4c9da246074.png)

**Comment by thom4parisot** [comment]
@xkcoding well, right now I can't tell sadly 😞 Maybe there is an edge case which has not been taken in consideration with the plugin and does not make the error explicit enough.

> What is the value of the _config.yml in the algolia block? (clear our the apiKey when you paste just in case it would enable to write in the index).

Does `indexName` match the name of your index in algolia?

![image](https://user-images.githubusercontent.com/138627/28614494-f1eec12e-71ed-11e7-8f54-c70e7a2753e7.png)

Does `applicationID` match the value of your application id in algolia?

![image](https://user-images.githubusercontent.com/138627/28614549-2040045c-71ee-11e7-976f-e2c3ed564b22.png)

**Comment by neroxps** [comment]
@oncletom sorry for the late reply
![hexo-algolia-01](https://user-images.githubusercontent.com/8503224/28650253-175ea982-72ad-11e7-9776-a18c515e16bc.png)

system:MacOS 10.12.3
NerodeMacBook-Pro:~ nero$ hexo -v
hexo-cli: 1.0.3
os: Darwin 16.4.0 darwin x64
http_parser: 2.7.0
node: 8.1.4
v8: 5.8.283.41
uv: 1.12.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b

****

```bash
NerodeMacBook-Pro:~ nero$ echo $HEXO_ALGOLIA_INDEXING_KEY
a88492a0212ebf6f74f996XXXXXXXXXX
```

$HEXO_ALGOLIA_INDEXING_KEY Operations：`addObject, listIndexes, deleteIndex, deleteObject`

****
_config.yml
```
algolia:
  applicationID: '4QAAXXXXXX'
  apiKey: 'a8f22345fd9f74b3680650xxxxxxxxxx' #Search-only API Key
  indexName: 'nero' #Confirmation is correct
```
![hexo-algolia-02](https://user-images.githubusercontent.com/8503224/28650263-266bdce2-72ad-11e7-9aa3-540d1694cf9e.png)

![hexo-algolia-03](https://user-images.githubusercontent.com/8503224/28650266-2a4e5e34-72ad-11e7-9df9-d690b992ff5e.png)

**Comment by thom4parisot** [comment]
Hm, I suspect there is a possible issue related to the content.

Any chance @neroxps or @xkcoding hexo instance is open on GitHub? If so, I would quite like to try to index its content in a temporary index of mine to test things a bit further.

Hopefully it will help troubleshooting things a bit better for all of us 😃

**Comment by zjh1943** [comment]
exactly the same problem. right applicationID, apiKey, apiKey and $HEXO_ALGOLIA_INDEXING_KEY. then the same error.

**Comment by zjh1943** [comment]
```
INFO  [Algolia] Testing HEXO_ALGOLIA_INDEXING_KEY permissions.
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error
    at success (/Users/zjh/Project/zjh1943.github.io/node_modules/algoliasearch/src/AlgoliaSearchCore.js:351:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

**Comment by thom4parisot** [comment]
Thanks for reporting the issue as well @zjh1943. I will try to use https://github.com/zjh1943/zjh1943.github.io/tree/source to try reproducing the problem if that's okay with you?

**Comment by zjh1943** [comment]
@oncletom It's okay with me. I will push the latest code. then you can get the `algolia` config

**Comment by zjh1943** [comment]
@oncletom Problem is that you do not have the `adminApiKey` which will export to `$HEXO_ALGOLIA_INDEXING_KEY`. Do you need one ?

**Comment by zjh1943** [comment]
@oncletom I think I have found the reason.
I set the `Admin Api Key` to `HEXO_ALGOLIA_INDEXING_KEY ` this morning. It failed. 
Just now, I create a brand new api key, set up the right permissions, and it works. 
I'm so sorry that I supposed that `Admin Api Key` have all the permissions, which is more powerful than a new index key.

**Comment by thom4parisot** [comment]
Hm, the `adminApiKey` has been removed from the `_config.yml` so it is not taken in consideration by the plugin. Maybe I can add a warning about this.

Also, when you write:

> I create a brand new api key, set up the right permissions, and it works.

Are the _right permissions_ the one mentioned in the README or did you have to add some more?

**Comment by zjh1943** [comment]
@oncletom Yes, exactly same as the README. Your guide is exactly right. And if the steps ( 1, 2, 3, 4...)  are more clear, it will be perfect. By the way, your code helps me very much. THX!

**Comment by zpf124** [comment]
@zjh1943  @oncletom 
I also appeared on this issue and solved it. This is not a bug...
My English may be so bad or Some of the getstart documents are confusing，some people like me expot env used the admin key  or search only key , but it should be create new apikey for the make index.

![Correct ](https://user-images.githubusercontent.com/11630361/28741330-8f9c94c8-7446-11e7-88d3-8aaa45e87688.png)

**Comment by thom4parisot** [comment]
I'm all in favour of making the README less confusing and easier to understand 🙂 

I did not know the admin key did not work actually. I will have a go at it and make the error more understandable.

Thanks for helping folks 👍

**Comment by xuelingzhizun** [comment]
@oncletom 
# 1.Error
I also found this problem
```
INFO  [Algolia] Testing HEXO_ALGOLIA_INDEXING_KEY permissions.
INFO  Start processing
INFO  [Algolia] Identified 23 posts to index.
INFO  [Algolia] Start indexing...
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error
    at success (/home/xuefeng/code/test1/node_modules/algoliasearch/src/AlgoliaSearchCore.js:351:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
# 2.Environment
```
systemOS: Ubuntu 17.04
hexo-cli: 1.0.2
hexo: 3.3.8
themes: next 5.1.0
node: v8.2.1
```

# 3.English:
My English is very poor, the following words are translated by Google translation。

## 3.1 Description
I'm sure my settings have been set up by rules, after many experiments I found that this error is hexo program under the '_post' folder caused by the `md` file.And I found the files which can  lead error  appears have a common feature that size is too large。

The files shown in the screenshot below are on this website[http://git.oschina.net/xfnotes/xfnotes/tree/backmd/](http://git.oschina.net/xfnotes/xfnotes/tree/backmd/) 

Hope this feedback is helpful in solving the problem

## 3.2 Can be passed files when `hexo a`
![image](https://user-images.githubusercontent.com/13586705/29053867-05b930f4-7c25-11e7-9550-1507bd455dc5.png)


## 3.3 Can not pass the `hexo a` command file
![image](https://user-images.githubusercontent.com/13586705/29053792-b75be33e-7c24-11e7-8827-29d5b4d60273.png)

# 中文:
我确信我的设置都已经按要求设置好了,经过我多次实验发现，这个错误是由hexo程序下的‘_post’文件夹中的md文件导致的。我发现不能导致错误的文件都有一个共同特点，太大。

下面展示的截图中的文件都在这个网站里[http://git.oschina.net/xfnotes/xfnotes/tree/backmd/](http://git.oschina.net/xfnotes/xfnotes/tree/backmd/)
希望这个反馈对解决问题有所帮助

## 可以通过`hexo a`的文件
![image](https://user-images.githubusercontent.com/13586705/29053867-05b930f4-7c25-11e7-9550-1507bd455dc5.png)

## 不可以通过`hexo a`的文件
![image](https://user-images.githubusercontent.com/13586705/29053792-b75be33e-7c24-11e7-8827-29d5b4d60273.png)

**Comment by neroxps** [comment]
@oncletom 

I excluded this file after hexo a passed.

[Hotpatch-02.txt](https://github.com/oncletom/hexo-algolia/files/1210845/Hotpatch-02.txt)

@xuelingzhizun  感谢你的提醒，根据你的提醒，我筛选了我的文件发现是这篇文件篇幅太大，我把他分割成三份，依然不能通过 hexo a。

**Comment by thom4parisot** [comment]
Thanks @neroxps, very helpful :-) It should help identify the problem and fix it.

**Comment by thom4parisot** [comment]
@neroxps hm, I downloaded `Hotpatch-02.txt` and renamed it as `_posts/Hotpatch-02.md`, ran `hexo algolia` and did not encounter the problem.

I saw in your git history you upgraded hexo, do you still encounter the issue while indexing then?

**Comment by thom4parisot** [comment]
Okay, I have managed to identify the problem — hopefully the next patch version of the plugin will make the errors clearer, when they still happen.

**Comment by neroxps** [comment]
@oncletom 
I exclude Hotpath.md and then run hexo a.

I did not generate an index for Hotpath.md.

The following is the full text of Hotpath.md

[Hotpatch.txt](https://github.com/oncletom/hexo-algolia/files/1217021/Hotpatch.txt)

I do not speak English, so English is generated by Google translation.

I hope my feedback will help you.

**Comment by thom4parisot** [comment]
Try with `hexo-algolia@1.2.1`, it should do a better job at telling us what are the errors.

You should will be able to fix the problems by reading the error messages 🤞

**Comment by Caij** [comment]
@oncletom 
+ hexo-algolia@1.2.1
Still have such this problem.  I think it should be the same problem with @xuelingzhizun description.

File:
[2015-08-12-Activity启动流程.txt](https://github.com/oncletom/hexo-algolia/files/1253672/2015-08-12-Activity.txt)

**Comment by thom4parisot** [comment]
@Caij okay, will have a look at it 🙂  Thanks for sharing the problematic file.

**Comment by thom4parisot** [comment]
Thanks @Caij, I can reproduce the problem with your provided file 👍

**Comment by thom4parisot** [comment]
Hey folks,

it seems the error was due to a size limit on the algolia side of things. An indexed object could not be bigger than 10kB. So I _removed_ the `post.content` from the indexed properties.

851a0b1 revealed this problem via this kind of error:

```
ERROR [Algolia] Record at the position 25 objectID=48e3aaf910d12a8dcf96ac00cf692c52150131db is too big size=132684 bytes. Contact us if you need an extended quota
```

Pick up the new version (`hexo-algolia@1.2.2`) and reopen this issue if needed 👍
