### ISSUE TITLE
Please set an `HEXO_ALGOLIA_INDEXING_KEY` environment

### ISSUE THREAD

**Issue by idonkeyliu** [oncletom/hexo-algolia#27]
![qq 20170929115212](https://user-images.githubusercontent.com/6152000/31000230-ba4f22ca-a50c-11e7-8b05-15f2ecb8acc0.jpg)

window7:
set HEXO_ALGOLIA_INDEXING_KEY='*****', do not work.

**Comment by thom4parisot** [comment]
Hey @idonkeyliu, have you followed the link in the error message to learn how to set environment variables? I don't use Windows but if you find out how to set an environment variable on Windows, tell us.

Maybe https://npmjs.com/cross-env contains some info on how to do it.

**Comment by idonkeyliu** [comment]
Hi, oncletom, Thank you for your reply.

I try it in my MacBook, then it do not works too.

So I guess network is a problem.

I switch my MacBook's net from wifi to 4G. It works.

Thank you  again.

**Comment by thom4parisot** [comment]
Oh, weird. Glad you managed to find out the reason of the problem 🙂
