### ISSUE TITLE
Question about Plugin state

### ISSUE THREAD

**Issue by AdrieanKhisbe** [oncletom/hexo-algolia#3]
Hello @borisschapira :smiley: 

The subtitle of your repo is _An incomplete attempt to plug Algolia in Hexo_
What is missing it prior the 0.2.0, or is ths till missing basic features?

**Comment by borisschapira** [comment]
I stopped developping that 6 month ago as I switched to Jekyll which is faster, but what I didn't get right is the ability to push content to algolia incrementaly (i.e : you modify a typo, you don't have to push all of your website again). 

Moreover, the way I pushed was not very subtle and didn't allow the search to target a specific paragraphe (see example of such targetting on https://borisschapira.com, typing "blocker" : the proposed post target a specific paragraph containing the keyword).

**Comment by AdrieanKhisbe** [comment]
Thanks for the details @borisschapira :)
I'll give a deeper look when I'll dig into hexo.
