### ISSUE TITLE
TypeError: data.tags.map is not a function

### ISSUE THREAD

**Issue by sli1989** [oncletom/hexo-algolia#33]
The related hexo-next issue is [here](https://github.com/theme-next/hexo-theme-next/issues/212).

```
$ hexo algolia
INFO  [Algolia] Testing HEXO_ALGOLIA_INDEXING_KEY permissions.
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: data.tags.map is not a function
    at F:\MyBlog\Hexo\node_modules\hexo-algolia\lib\command.js:113:39
    at Array.map (<anonymous>)
    at F:\MyBlog\Hexo\node_modules\hexo-algolia\lib\command.js:99:37
    at <anonymous>
```

Is this the Algolia's problem? It seems confused. Need to delete the the section of https://github.com/oncletom/hexo-algolia/blob/b04716a7ba70940094049a6816c767543404a424/lib/command.js#L112-L116

**Comment by thom4parisot** [comment]
Ah! I assume you have at least one post which does not have tags in it?

Or have a `tags` front matter information which is not a list of tags (maybe just a string).

**Comment by sli1989** [comment]
Oh, seems like [that](https://github.com/theme-next/hexo-theme-next/issues/212#issuecomment-378858343).

**Comment by AlanKeene** [comment]
@oncletom 
I have some other information to tell you about this bug.
Yesterday my md file in `hexo/source/tags/index.md` like this:
```
---
title: tags
date: 2018-04-03 17:02:35
tags: "tags"
comments: false
---
```
and today I find it's last theme's  definition method，it's not fit for the NexT theme.
It's should be like this to make the tags page active:
```
---
title: tags
date: 2018-04-03 17:02:35
type: "tags"
comments: false
---
```

But I don't know this change whether influences this bug or not.

**Comment by thom4parisot** [comment]
Hey,

I think you gave the answer 🙂 

With

```yaml
---
title: {{ title }}
date: {{ date }}
tags:
categories:
---
```

… the `tags` key is empty and considered as a `string` or something.

I'm happy to change the code of this plugin to make sure tags are indexed if they are an array structure.
