### ISSUE TITLE
Can not delete(update) index when using hexo a

### ISSUE THREAD

**Issue by tw19941212** [oncletom/hexo-algolia#35]
first I create a new post, then hexo a which can update index in algolia. but after I delete my post and use hexo a which cannot delete the index I create in algolia?

**Comment by thom4parisot** [comment]
Have you tried with the `--flush` command line option?

If you use it (like `hexo algolia --flush`), it will remove index content, then it will index content.

Let me know if it solves your problem.

**Comment by tw19941212** [comment]
It doesn't help me.
`INFO  [hexo-algolia] 4 pages and posts to index.
INFO  [hexo-algolia] Clearing index...
INFO  [hexo-algolia] Indexing chunk 1 of 1 (50 items each)
INFO  [hexo-algolia] Indexing done.`
That was my terminal output when using 'hexo algolia --flush'. It seems really do clearing index but actually not.
the picture is my ACL of algolia, anything wrong?
![default](https://user-images.githubusercontent.com/35515510/50152142-d7ae0c00-02fd-11e9-98e6-4689b3733fd5.png)

**Comment by thom4parisot** [comment]
Hello @tw19941212, I have double checked the flushing. It works well.

I published a patch release (`v1.3.1`) to ensure the indexing happens really after the flushing.

If it does not work as expected, I'd be curious to see a screenshot of the `Indices` panel of your index. Your settings look good.

**Comment by tw19941212** [comment]
@oncletom I'm so sorry for misunderstanding what `--flush` means. I just think it will clear all index.
I tested v1.3.0 and v1.3.1, all perform well with `--flush`.
Thanks, it's great to work with it!

**Comment by thom4parisot** [comment]
> I just think it will clear all index.

Ah, that's a good point. I will think of a clearer way to phrase this information in the README and the CLI instructions.
