### ISSUE TITLE
README.md typos

### ISSUE THREAD

**Issue by ifyour** [oncletom/hexo-algolia#37]
![image](https://user-images.githubusercontent.com/15377484/50294481-eee12b00-04b0-11e9-95ee-40c8d383f283.png)

> const client = algoliasearch(algoliaConfig.applicationID, algoliaConfig.apiKey);

This is `applicationId`, not `applicationID`. 🌚

**Comment by thom4parisot** [comment]
What you show here is the output of a DOM value.
`<meta property="algolia:search" data-application-id="...">` is 

The configuration key is `applicationID`, and it populates the aforementioned attribute.
Cf. https://github.com/oncletom/hexo-algolia/blob/3853bd5c85500cfb77b377b99459650f6acac18b/lib/helpers/search_config.js#L8-L10

I understand it's confusing, and I'll think of something to make it easier to configure the Algolia Client, which I assume is the main issue.

**Comment by ifyour** [comment]
https://github.com/oncletom/hexo-algolia/blob/3853bd5c85500cfb77b377b99459650f6acac18b/lib/helpers/search_config.js#L8-L10

Here is correct. because this `applicationID` defined in `_config.yml`. 

In our site, we should get this `id` from `meta`, but this default value is `applicationId`. Just a typo in README.md.

**Comment by ifyour** [comment]
![image](https://user-images.githubusercontent.com/15377484/50299464-99ab1680-04bc-11e9-89ed-40725e359d01.png)

LoL~ 😎

**Comment by thom4parisot** [comment]
Aaah, yes I see, on this line:

```js
const client = algoliasearch(algoliaConfig.applicationID, algoliaConfig.apiKey);
```

Right sorry, I misunderstood which application ID you were referring to.
I'm thinking of aligning variable spelling to avoid confusion.
