### ISSUE TITLE
Alway show that  Please set an `HEXO_ALGOLIA_INDEXING_KEY` environment variable to enable content indexing when the computer startup.

### ISSUE THREAD

**Issue by jerryc127** [oncletom/hexo-algolia#40]
I set the environment variable and it work.
But when i shutdown and restart the computer.
it show that Please set an `HEXO_ALGOLIA_INDEXING_KEY` environment variable to enable content indexing.

Is this normal? need to set an `HEXO_ALGOLIA_INDEXING_KEY` environment variable when the computer start ?

**Comment by thom4parisot** [comment]
Hi @jerryc127,

Indeed, the environment variable set with `export` is tight to the lifetime of your shell session. So it's normal.

Environment variables are made available to any program which run on a computer a given time (from within the same shell session) so it depends how much you trust the other programs you run. A rogue npm module could scan the env variables and leak them to someone else.

Personally, I add an environment variable at the system level only if I use them so often I'm bored to type them again.

I suspect there is a way to use the operating system "keyring" to store and prompt the key content securely but I have not looked into that yet.

If you use continuous integration, then I'd recommend to run the indexer there, and to store the key as an encrypted environment variable. [This is how I do on my blog](https://github.com/oncletom/oncletom.io/blob/master/.travis.yml).

Does it answer your question? Do you think of something else?

**Comment by jerryc127** [comment]
thx. i choose to add an environment variable at the system level

**Comment by thom4parisot** [comment]
Cool 🙂 let me know if you encounter any problem or wonder about something else.
