### ISSUE TITLE
I always have 0 articles to index

### ISSUE THREAD

**Issue by thom4parisot** [oncletom/hexo-algolia#5]
It takes my blog ~4sec to load its files w/ hexo@3.2

I tried clearing out the `./public` folder but it seems the indexing happens before the load ever happened:

![image](https://cloud.githubusercontent.com/assets/138627/18092409/168f0878-6ec4-11e6-9d4b-73645b77657a.png)

It seems the rendering happens _after_ `generateAfter` has been emitted:

![image](https://cloud.githubusercontent.com/assets/138627/18092599/cb46fd7a-6ec4-11e6-9f81-f7dacd3083fb.png)

**Comment by borisschapira** [comment]
Wow, to be honest, I've let this project down monthes ago. Do you want to adopt it?

**Comment by thom4parisot** [comment]
Hm, maybe not, I found: https://github.com/LouisBarranqueiro/hexo-algoliasearch

EDIT: have the same issue with it. Weird.
